name: Test
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5.x, 3.6.x, 3.7.x, 3.8.x, 3.9.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    - name: Test with pytest
      run: |
        pytest --cov=. --cov-report xml --cov-report term
    - name: Report coverage
      if: matrix.python-version == '3.9.x'
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.cc_test_reporter_id }}
      run: |
        ./cc-test-reporter after-build --exit-code $?
